name: Keepalive Workflow

on:
  schedule:
    - cron: "0 0 1 */2 *" # Runs every 2 months
  workflow_dispatch: # Allows manual trigger

jobs:
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Make keepalive commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Chore: keepalive activity update"
          git push
